name: Python application matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12' ]
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [[ -f requirements.txt ]]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
  e2e:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Run Simple Math
      run: |
        export CMD_VALUE="python simple_math.py 4 5"
        export OUTPUT=$($CMD_VALUE)

        echo "### Run Simple Math" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "#### Add" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "I/P: 4 5" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "O/P: ${OUTPUT}" >> $GITHUB_STEP_SUMMARY

        echo "# I/P: 4 5" >> e2e.txt
        echo "" >> ec2.txt
        echo "# O/P: ${OUTPUT}" >> e2e.txt

    - name: Upload ec2 output
      uses: actions/upload-artifact@v4
      with:
        name: e2e.txt
        path: e2e.txt
        if-no-files-found: error    
  
