name: Python application matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12' ]
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [[ -f requirements.txt ]]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest

  e2e:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        inputs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Run Simple Math
      run: |
        export CMD_VALUE="python simple_math.py ${{ matrix.inputs }} 5"
        export OUTPUT=$($CMD_VALUE)

        # Log to GitHub step summary
        echo "### Run Simple Math" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "#### Add" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "I/P: ${{ matrix.inputs }} 5" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "O/P: ${OUTPUT}" >> $GITHUB_STEP_SUMMARY

        # Create and append results to results.txt in the workspace
        echo "# I/P: ${{ matrix.inputs }} 5" >> results.txt
        echo "# O/P: ${OUTPUT}" >> results.txt
        echo "" >> results.txt

    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: e2e-results-${{ matrix.inputs }}
        path: results.txt

  combine_results:
    needs: e2e
    runs-on: ubuntu-latest
    steps:
    - name: Download all results artifacts
      run: |
        for i in {1..60}; do
          echo "Downloading artifact for input $i"
          mkdir -p results
          actions/download-artifact --name e2e-results-$i --path results/
        done

    - name: Combine results
      run: |
        echo "# Combined Results" > combined_results.txt
        for file in results/*.txt; do
          cat "$file" >> combined_results.txt
        done

    - name: Upload combined results
      uses: actions/upload-artifact@v4
      with:
        name: combined_e2e_results
        path: combined_results.txt

